export type Category = 'Markets' | 'Learn' | 'Research' | 'Businesses' | 'Fin × Tech';
export interface Article { slug: string; title: string; category: Category; tag: string; excerpt: string; body: string[]; readingTime: string; featured?: boolean; }

const paragraph = (text: string) => text.split('\n\n');
export const articles: Article[] = [
 { slug:'basic-vocabulary', title:'BASIC VOCABULARY', category:'Learn', tag:'Finance Basics', excerpt:'The very basic terms you need to know to get started.', body:[], readingTime:'Reference', featured:true },
 { slug:'ai-earnings-call-research', title:'AI Earnings Call Research', category:'Research', tag:'Fin × Tech', excerpt:'A research framework for reading AI signals in earnings calls.', body:paragraph(`Stop asking AI to simply summarize your earnings-call transcripts.

Instead, ask these six questions to extract much more useful information from them.

Upload the last 8–12 earnings-call transcripts to an AI tool such as NotebookLM or Claude.

Instead of asking:

“Summarize these documents.”

Ask:

1. Track the Narrative

“Across the last 8 quarters, what are the core recurring themes in management commentary, and how have they evolved?”

2. Decode Demand Shifts

“How has management's language around demand changed over time, especially during weaker quarters?”

3. Assess Accountability

“Identify instances where management attributed performance to external factors versus internal execution.”

4. The Reality Check

“Compare management's previous promises and expectations with the company's actual performance in subsequent quarters.”

5. Spot Structural Issues

“What risks were repeatedly highlighted in earlier earnings calls, and how were they subsequently resolved, mitigated, ignored or allowed to persist?”

6. Read Between the Lines

“Track changes in management's tone, confidence and level of certainty. How does this differ between stronger and weaker quarters?”

These questions force the AI to look for patterns across time, rather than simply summarizing each call individually.

But remember:

AI is extracting and organizing information from the documents.

It can also make mistakes or miss context.

Use the output as a research aid, not as a substitute for reading the underlying transcripts or making your own investment judgment.`), readingTime:'4 min', featured:true },
 { slug:'colgate-toothpaste', title:'The Colgate Toothpaste Tube', category:'Businesses', tag:'Strategy', excerpt:'A business lesson hidden in an everyday consumer product.', body:paragraph(`What if I told you that a tiny change in a toothpaste tube could increase a company's revenue without increasing its price?

There's a famous story about Colgate where the company supposedly increased the diameter of the opening of its toothpaste tube from 5mm to 6mm.

Why would that matter?

Because increasing the diameter by just 1mm increases the cross-sectional area of the opening by roughly 44%.

So every squeeze could dispense significantly more toothpaste.

The result?

Consumers would finish the tube faster and need to buy another one sooner.

And that's where the finance gets interesting.

Colgate doesn't necessarily need to acquire a new customer.

If the same customer normally buys 6 tubes a year and the larger opening increases consumption, they might buy 7 or 8.

That increases purchase frequency, annual revenue per customer and potentially customer lifetime value without necessarily increasing the selling price.

And there's an important economic trade-off.

The company is giving away more toothpaste per purchase, so its cost of goods sold also increases.

The strategy only makes financial sense if the additional revenue and contribution margin from higher purchase frequency outweigh the additional product cost.

And that's the real lesson:

Sometimes revenue growth isn't about getting more customers.

It's about increasing the revenue generated by each existing customer.`), readingTime:'3 min', featured:true },
 { slug:'ai-humans', title:'AI + Humans', category:'Fin × Tech', tag:'AI', excerpt:'Meta, Ford, McDonald’s and Taco Bell show different ways AI meets work.', body:paragraph(`PM Narendra Modi's Facebook post was temporarily removed by Meta's systems.

And that's not the only recent example of AI falling short of expectations.

Meta said the post was removed in error and was subsequently restored, with the company attributing the incident to a problem with its automated systems.

Ford is another interesting example.

The company brought back around 350 experienced engineers after its automated and AI-assisted quality systems failed to deliver the results Ford wanted.

The engineers are now working alongside AI rather than simply being replaced by it.

Then there's McDonald's.

A security flaw in its AI-powered hiring platform exposed data associated with roughly 64 million job applicants after researchers discovered that an account was protected by the password “123456” and lacked multi-factor authentication.

And Taco Bell's AI drive-thru system became a viral example of what happens when AI encounters unexpected customer behaviour.

One notorious incident involved someone attempting to order 18,000 cups of water.

But there's an important twist:

Taco Bell didn't abandon the technology.

It's actually expanded its voice-AI system to more than 890 U.S. restaurants.

So perhaps the lesson isn't that AI is failing.

It's that companies may sometimes be overestimating what AI can reliably do without human oversight.

And if businesses eventually realize that AI works best alongside humans rather than instead of them, could that create another wave of demand for technology and IT talent in India?

Follow for more.`), readingTime:'4 min', featured:true },
 { slug:'trading-comps-vs-precedent-transactions', title:'Trading Comps vs Precedent Transactions', category:'Research', tag:'Valuation', excerpt:'Two common valuation methods, and the different questions they answer.', body:paragraph(`Trading comps and precedent transaction analysis are both relative valuation methods.

But they answer different questions.

Comparable company analysis, or trading comps, values a company using the current trading multiples of similar publicly listed companies.

It tells you what public-market investors are currently paying for comparable businesses.

Precedent transaction analysis values a company using multiples from previous M&A transactions involving similar businesses.

It tells you what acquirers have actually paid in comparable deals.

And there's an important difference.

Trading comps generally reflect the market value of a minority, freely tradable interest.

Precedent transactions generally involve the acquisition of control.

Because an acquirer is buying control — and may also expect synergies — transaction multiples often come out higher than trading multiples.

But that's not a rule.

Deal-specific factors, market conditions, synergies and the quality of the comparable transactions can all affect the multiple.

So in simple terms:

Trading comps ask, “What does the public market currently pay for a comparable business?”

While precedent transactions ask:

“What have actual acquirers paid to obtain control of comparable businesses?”

That's why they're both useful — but for different valuation questions.`), readingTime:'4 min', featured:true },
 { slug:'uber-driver-engagement', title:'Uber Driver Engagement', category:'Businesses', tag:'Strategy', excerpt:'How a platform thinks about driver engagement.', body:paragraph(`Uber doesn't own most of the cars on its platform.

So one of its biggest financial problems is actually keeping drivers active.

Think about the economics.

Every time a driver completes a ride, Uber has an opportunity to generate another booking.

But the driver can also do something else:

Go home.

Switch to Lyft.

Take a break.

Or simply stop accepting rides.

That's why the driver app is designed to immediately notify drivers when another ride is available — including the familiar chime and visual alert.

And this isn't just a product-design decision.

It's a unit economics decision.

Imagine Uber earns an average of $5 in revenue from each completed trip.

If a driver completes 10 trips a day, that's $50 of revenue for Uber from that driver.

If better driver engagement means that driver completes 12 trips instead, Uber potentially generates another $10 without having to acquire another rider.

Now scale that across millions of trips.

The economics become significant.

This is why driver retention matters so much to a marketplace like Uber.

The company isn't just trying to attract more riders.

It needs enough drivers to keep the marketplace liquid — and every additional trip from an existing driver can increase revenue per active driver and platform utilization.

So that little chime on a driver's phone isn't just a sound.

It's part of the machinery that keeps Uber's marketplace running.`), readingTime:'3 min', featured:true },
 { slug:'depreciation-three-financial-statements', title:'Depreciation and the Three Financial Statements', category:'Learn', tag:'Corporate Finance', excerpt:'A $10 increase in depreciation does not reduce net income by the full $10.', body:paragraph(`What is the effect of increasing depreciation by $10 on the three financial statements?\n\nMost people answered that net income will fall by $10, cash flow from operations will increase by $10, and total assets will fall by $10.\n\nBut that's not the complete answer.\n\nWhat we need to understand is that depreciation is a non-cash and tax-deductible expense.\n\nYour profit before tax will fall by $10. But assuming a 30% tax rate, your tax expense will decrease by $3.\n\nThis means the impact on net income is just a $7 decrease.\n\nIn the cash flow statement, net income starts $7 lower, and there will be an increase in depreciation of $10.\n\nThis means the net cash flow from operations will increase by $3.\n\nOn the balance sheet, PP&E will fall by $10, cash will increase by $3, and the net effect on retained earnings will be a $7 decrease.\n\nThat's the final answer most people look for.`), readingTime:'2 min', featured:true },
 { slug:'samsung-expectations', title:"Samsung's Record Quarter Wasn't Enough", category:'Markets', tag:'Businesses', excerpt:'Why market expectations can matter as much as the result itself.', body:paragraph(`In July, Samsung recorded the best quarter in its history. Operating profit jumped almost 1,800% year over year.

And yet, the stock price crashed almost 7%.

But why?

This is one of the most fundamental concepts in financial markets:

Stock prices don't react to the news. They react to the news relative to expectations.

For example, imagine a company's earnings are expected to grow by 20% next quarter.

That expectation is already reflected in the stock price.

So if the company actually grows earnings by 17%, that's still great growth — but it falls short of what investors were expecting.

And the stock price can fall.

That's essentially what happened with Samsung.

Samsung's second-quarter operating profit was expected to be extremely strong because the AI boom had driven memory-chip prices sharply higher.

Samsung benefited enormously from this. Its preliminary operating profit came in at around KRW 89.4 trillion, nearly 19 times the previous year's figure, and above analyst expectations.

But investors had already priced in a huge amount of that optimism.

At the same time, concerns were growing about how sustainable the AI boom and elevated memory prices were, as well as future semiconductor capacity and competition.

So despite Samsung delivering record-breaking numbers, the stock fell almost 7%.

The lesson?

In financial markets, it's not enough to ask, "Is the news good?"

You have to ask:

"Is the news better or worse than what investors were already expecting?"`), readingTime:'3 min', featured:true },
 { slug:'big-mac-index', title:'The Big Mac Index', category:'Learn', tag:'Economics', excerpt:'A burger price can make purchasing power parity easier to understand.', body:paragraph(`Did you know that the price of a burger can tell you more about the economy than the internet exchange rate?\n\nIn 1986, the concept of the Big Mac Index was introduced by The Economist, which compares the prices of a Big Mac across different countries.\n\nYou might get jealous of your friend who earns $100,000 in the US, which is roughly around ₹95,00,000 in India, while you are stuck here earning ₹38,00,000 per annum.\n\nBut that's where things get interesting.\n\nThe price of a Big Mac in the US is $6.22, while in India it's just ₹236, which is around $2.46.\n\nThis means that with $6 in hand, I can buy one burger in the US and roughly 2.5 burgers in India.\n\nAnd by making some simple calculations, we can see that earning ₹38,00,000 in India can give us roughly the same standard of living as earning $100,000 in the US — and, of course, ceteris paribus.\n\nJust to clarify, the Big Mac Index is simply an informal index created by The Economist to make purchasing power parity (PPP) easier to understand and estimate. It's not a precise measure of someone's actual standard of living.\n\nLet me know your thoughts on this.`), readingTime:'2 min' },
 { slug:'shrinkflation', title:'Shrinkflation: The Price You Do Not See', category:'Learn', tag:'Economics', excerpt:'Pears reduced from 60g to 57g while the ₹20 price tag stayed intact.', body:paragraph(`A soap you've been getting for ₹20 for the past 10 years might not be the same size anymore.\n\nThat's exactly what happened with Pears from HUL, where the quantity of the soap was reduced from 60g to 57g while the price tag of ₹20 remained intact.\n\nThis is a prime example of a concept known as shrinkflation.\n\nNow imagine if the price had increased directly from ₹20 to ₹22. That visible increase in price would have had a higher impact on demand compared to simply reducing the quantity.\n\nAnd that's where the psychological impact of shrinkflation comes in.\n\nA small and unnoticed decrease in quantity creates a psychological impact among consumers — they feel like they're buying the same product for the same price, even though they're actually paying more per gram for the same product.\n\nBut companies generally don't use shrinkflation simply to increase their profits. It is mostly used by FMCG companies to protect their margins when production costs rise, without angering consumers with a visible price increase.\n\nSo the next time you go to buy a soap, don't just look at the price. Also look at the quantity.\n\nComment down your thoughts.`), readingTime:'2 min' },
 { slug:'npv-vs-irr', title:'NPV vs IRR', category:'Learn', tag:'Corporate Finance', excerpt:'The higher return is not always the project that creates the most value.', body:paragraph(`Imagine you have two projects.\n\nProject A gives you a 30% IRR but a $500 NPV, while Project B gives you a 20% IRR and a $1,000 NPV.\n\nWhich one would you choose?\n\nIf you said Project A, you're wrong.\n\nNPV, or Net Present Value, tells you how much value a project has created after discounting its future cash flows to today's value.\n\nWhile IRR, or Internal Rate of Return, is the discount rate at which NPV is zero.\n\nSo IRR tells you the percentage return, while NPV tells you the actual value created.\n\nThis becomes important when you're choosing between two mutually exclusive projects. A smaller project can have a higher IRR but a lower NPV, while a larger project can create significantly more value.\n\nThat's why NPV is generally preferred over IRR because the main goal of corporate finance is to maximize shareholder value.\n\nIRR also has a major drawback: it assumes that a project's cash flows are reinvested at the IRR itself, which can be pretty unrealistic.`), readingTime:'2 min' },
 { slug:'swiggy-iocc', title:'Swiggy, Foreign Ownership and IOCC', category:'Businesses', tag:'Markets', excerpt:'A look at ownership, operating companies and the market.', body:paragraph(`In July, Swiggy's stock rallied by around 7%.

But nothing fundamentally changed in the business overnight — except for one important thing.

Swiggy's aggregate foreign ownership fell from above 50% to 49.76% as of July 6.

But why does a 0.25 percentage-point difference matter so much?

Because it brought Swiggy one step closer to qualifying as an Indian-Owned and Controlled Company, or IOCC.

And here's why that matters.

Under India's foreign investment rules, an e-commerce company with foreign investment cannot operate an inventory-based e-commerce model, where the company itself owns the inventory and sells it directly to consumers.

So Instamart has historically operated under a marketplace-type structure rather than simply owning the products it sells.

But if Swiggy qualifies as an IOCC, it can potentially move towards an inventory-based model.

Imagine a consumer buys ₹1,000 worth of products.

Under a marketplace model, Swiggy might earn a commission — let's say 10%, or ₹100.

But under an inventory-based model, Swiggy could potentially purchase the inventory from a seller for, say, ₹800 and sell it to the consumer for ₹1,000.

That means the economics can look very different, because Swiggy could capture the gross margin on the product, rather than simply earning a marketplace commission.

In simple words, Instamart has traditionally operated more like a marketplace, while an inventory-based model would allow it to operate more like a retailer.

And that's why investors paid so much attention to a seemingly tiny 0.25 percentage-point change in foreign ownership.

One important clarification: the 49.76% figure alone did not immediately make Swiggy an IOCC. Swiggy subsequently obtained shareholder approval in August for the changes needed to move toward that status.

So sometimes, a tiny change in a number can have a very large impact on how a business can operate.`), readingTime:'3 min' },
 { slug:'reverse-dcf', title:'Reverse DCF', category:'Research', tag:'Valuation', excerpt:'Start with the share price and ask what the market must be expecting.', body:paragraph(`Instead of asking, “What is this company worth?”

What if we ask:

“What is the market already expecting?”

That's exactly what a Reverse DCF helps you understand.

A normal DCF starts with assumptions about revenue growth, margins, cash flows and the discount rate to estimate what a company should be worth.

A Reverse DCF starts with the current market price and works backwards to identify the assumptions that would justify that valuation.

For example, you can calculate the company's current enterprise value and then keep certain assumptions fixed — such as revenue growth, margins and terminal growth — and solve for the implied discount rate.

Let's say the model implies an 8% discount rate.

But based on the company's risk and capital structure, you believe a 10% discount rate is more appropriate.

That tells you the current valuation is relying on a lower required return than your assumptions would justify.

And that's why Reverse DCF is such a useful tool.

It doesn't just tell you what you think the company is worth.

It tells you what the market price is already assuming.`), readingTime:'3 min' },
 { slug:'dividends-buybacks', title:'Dividends and Buybacks', category:'Learn', tag:'Corporate Finance', excerpt:'Two ways companies return capital, and how tax changes the equation.', body:paragraph(`Most people think dividends are free money.

But they're not — and in India, dividend income can effectively face taxation at both the company and shareholder levels.

Let's take a simplified example.

Imagine a company makes $100 in profit before tax.

Assume a 25% corporate tax rate.

The company pays $25 in tax, leaving $75.

Now assume the entire $75 is distributed as a dividend and the shareholder is in a 30% tax bracket.

They pay another $22.50 in tax.

So from the original $100 of pre-tax profit, the shareholder is left with $52.50.

That's an effective tax burden of 47.5% in this simplified example.

This is one reason companies may prefer retaining earnings or returning capital through share buybacks rather than dividends, depending on the circumstances and tax regime.

But here's the interesting part:

India changed the taxation of buybacks in October 2024, shifting the tax burden to shareholders by treating buyback proceeds as deemed dividend.

However, that regime ended on March 31, 2026.

From April 1, 2026, the new Income-tax Act brought buybacks back under the capital-gains framework for ordinary shareholders.

So the tax treatment of dividends and buybacks can have a major impact on how companies choose to return money to shareholders.`), readingTime:'3 min' },
 { slug:'situational-awareness', title:'Situational Awareness, AI and Leverage', category:'Markets', tag:'Investing', excerpt:'A reminder that context matters when leverage meets a powerful narrative.', body:paragraph(`A 24-year-old AI investor turned a fund that started with around $225 million into one managing tens of billions of dollars.

And then, in July, it lost about 67% of its value.

This is the story of Leopold Aschenbrenner and his AI-focused hedge fund, Situational Awareness.

The fund had made extraordinary returns by betting heavily on the AI boom — particularly companies involved in chips, memory, data centers and energy infrastructure.

But there was one major problem:

Leverage.

The fund's public-equity portfolio was heavily leveraged, meaning it had borrowed money to make much larger bets.

When AI-related stocks started falling sharply in July, those losses were amplified.

As the value of the collateral fell, the fund faced margin pressure and was forced to liquidate much of its public-equity portfolio.

Citadel ultimately bought a large portion of those positions.

Around the same time, Citadel Securities published a note arguing that the Federal Reserve could surprise markets with a rate hike.

The Fed ultimately held rates steady, although three voting members dissented in favor of a hike.

The timing has led to speculation online about whether the rate-hike call contributed to the selloff.

But there is no established evidence that the call caused Situational Awareness's liquidation.

So what was the bigger lesson?

Was the problem the AI thesis?

Or was it using enough leverage that the fund couldn't survive a temporary move against that thesis?

That's the real question.`), readingTime:'3 min' },
 { slug:'sebi-closing-auction', title:"SEBI's Closing Auction Session", category:'Markets', tag:'Market Structure', excerpt:'What a closing auction session is designed to do.', body:paragraph(`SEBI just changed how the closing price is determined for a major group of Indian stocks.

And this can affect everything from institutional trading to index and ETF calculations.

Until now, the closing price was generally calculated using the volume-weighted average price of trades during the final 30 minutes of continuous trading.

But from August 3, 2026, SEBI introduced a Closing Auction Session, initially for stocks in the cash market that have F&O contracts.

Continuous trading ends at 3:15 PM.

Then the closing auction takes place, where buyers and sellers submit orders and the exchange determines an equilibrium price based on the orders received.

That price becomes the official closing price.

The auction runs through 3:35 PM, with order collection followed by order matching.

The idea is to make the closing price more representative of actual supply and demand at the end of the trading day, rather than relying on trades during the final 30 minutes.

But it also raises an important question:

Could concentrated order flow near the close create new opportunities for manipulation or distortions?

SEBI is already reviewing aspects of the closing-auction framework.

So was this a necessary improvement to price discovery, or does it create a new set of market-structure risks?

That's something worth watching.`), readingTime:'3 min' },
 { slug:'synthetic-cdo', title:'Synthetic CDO', category:'Learn', tag:'Finance', excerpt:'A plain-language look at a complex credit-market instrument.', body:paragraph(`What does a synthetic CDO actually mean?

First, let's understand a normal CDO.

Imagine a bank has ₹100 crore worth of loans.

Instead of waiting years for borrowers to repay those loans, the bank can package loans or other debt assets into a structured vehicle and issue securities to investors.

That structure is called a Collateralized Debt Obligation, or CDO.

Because the underlying assets have different levels of credit risk, the CDO is divided into different tranches, such as senior, mezzanine and equity tranches.

Now let's add the word synthetic.

Synthetic simply means getting exposure to the economics of an asset without directly owning that asset.

Instead of buying the underlying loans or bonds, I can use credit default swaps, or CDS, to take exposure to their credit risk.

For example, I could enter into a contract where I receive payments in exchange for taking on the risk of defaults in a reference portfolio.

If defaults occur, I may have to compensate the other party.

I now have exposure to the credit performance of that portfolio without actually owning the underlying loans.

That's why it's called a synthetic CDO.

Instead of being backed primarily by actual debt assets, it uses derivatives such as credit default swaps to create exposure to the credit risk of those assets.

After hearing “synthetic CDO” in The Big Short, I was really curious about what it actually meant.

And now you know.`), readingTime:'4 min' },
 { slug:'sector-rotation', title:'Sector Rotation', category:'Markets', tag:'Investing', excerpt:'Why market leadership moves as conditions and expectations change.', body:paragraph(`A great stock in a bad sector can still be a difficult investment.

As the economy moves through different phases, investors often rotate their money between different sectors.

This is known as sector rotation.

In the early stage of an economic recovery, interest rates may be falling and economic activity starts improving.

Cyclical sectors such as financials, consumer discretionary, industrials and real estate can benefit from improving economic conditions.

As the expansion matures and corporate earnings strengthen, sectors such as technology, industrials, energy and consumer discretionary can perform well, depending on the economic environment.

Later in the cycle, inflationary pressures may become more prominent and central banks may tighten monetary policy.

At that point, investors may increasingly look toward sectors with more defensive characteristics, such as healthcare and consumer staples.

And during a recession, those defensive sectors can sometimes provide more resilience than highly cyclical businesses.

But there's an important caveat:

Sector rotation isn't a fixed playbook.

Interest rates, inflation, earnings expectations and the specific economic environment can all change the pattern.

So understanding sector rotation won't automatically help you pick a winning stock.

But it can help you understand why an otherwise good company might be operating in an unfavourable part of the cycle.`), readingTime:'3 min' },
 { slug:'dcf', title:'DCF in 60 Seconds', category:'Learn', tag:'Valuation', excerpt:'The core intuition behind discounted cash flow valuation.', body:paragraph(`Walk me through a DCF in under 60 seconds.

Discounted Cash Flow, or DCF, is a valuation method used to estimate the intrinsic value of a business based on the present value of its future cash flows.

The first step is to forecast free cash flow.

You can use Free Cash Flow to the Firm, or FCFF, or Free Cash Flow to Equity, or FCFE.

The discount rate depends on which one you're using.

For FCFF, we typically use WACC, or Weighted Average Cost of Capital, which represents the required return for the company's debt and equity capital based on their market values.

For FCFE, we generally use the cost of equity instead.

The next step is to calculate the terminal value, which represents the value of the business beyond the explicit forecast period.

The two common approaches are the Gordon Growth method and the exit multiple method.

Finally, you discount the future cash flows and terminal value back to today.

With an FCFF DCF, this gives you the enterprise value.

The biggest limitation of a DCF?

It's highly dependent on your assumptions.

Even relatively small changes in growth, margins, reinvestment or the discount rate can have a significant impact on the valuation.

So a DCF doesn't give you a magical “correct” price.

It gives you a valuation based on your assumptions.`), readingTime:'1 min' }
];
export const getArticle = (slug: string) => articles.find((article) => article.slug === slug);
export const categorySlug = (category: Category) => category === 'Fin × Tech' ? 'fin-tech' : category.toLowerCase();
